"""
Régénère src/world/data/irelandGeo.json (côtes, îles, lacs, Shannon) depuis Natural Earth.
Inutile au quotidien : à lancer uniquement pour changer la précision des côtes.

Prérequis : Python 3 + `pip install shapely`
Usage (depuis la racine du projet) :
    mkdir -p /tmp/ne && cd /tmp/ne
    for f in ne_10m_land ne_10m_lakes ne_10m_lakes_europe ne_10m_rivers_lake_centerlines; do
      curl -sO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/$f.geojson
    done
    python3 <projet>/tools/build_geo.py && cp irelandGeo.json <projet>/src/world/data/
Données : Natural Earth (domaine public).
"""
import json
from shapely.geometry import shape, box, Polygon, LineString, MultiLineString
from shapely.ops import linemerge
BB = box(-11.2, 51.2, -5.2, 55.6)
def load(fn):
    out=[]
    for f in json.load(open(fn+'.geojson'))['features']:
        g = shape(f['geometry'])
        if g.intersects(BB): out.append((f['properties'], g.intersection(BB)))
    return out
def polys(g): return list(g.geoms) if hasattr(g,'geoms') else [g]
def flat(coords): 
    r=[]
    for x,y in coords: r += [round(x,3), round(y,3)]
    return r
land=[]
for p,g in load('ne_10m_land'):
    for pg in polys(g):
        if pg.geom_type!='Polygon': continue
        if pg.centroid.x > -5.9: continue
        land.append(pg)
land.sort(key=lambda p:-p.area)
out={'source':'Natural Earth 10m (public domain) - generated by tools/build_geo.py - DO NOT EDIT BY HAND','land':[],'lakes':[],'rivers':[]}
for i,pg in enumerate(land):
    s = pg.simplify(0.004 if i==0 else 0.002, preserve_topology=True)
    ring = list(s.exterior.coords)[:-1]
    out['land'].append(flat(ring))
for fn in ['ne_10m_lakes','ne_10m_lakes_europe']:
    for p,g in load(fn):
        for pg in polys(g):
            if pg.geom_type!='Polygon' or pg.area < 0.002: continue
            s=pg.simplify(0.003, preserve_topology=True)
            out['lakes'].append({'name':p.get('name') or 'Lough','ring':flat(list(s.exterior.coords)[:-1])})
sh=[]
for fn in ['ne_10m_rivers_lake_centerlines']:
    for p,g in load(fn):
        if p.get('name')=='Shannon':
            sh += [g] if g.geom_type=='LineString' else list(g.geoms)
m = linemerge(MultiLineString(sh))
lines = [m] if m.geom_type=='LineString' else list(m.geoms)
for l in lines:
    s=l.simplify(0.003)
    out['rivers'].append({'name':'Shannon','widthM':250,'line':flat(list(s.coords))})
json.dump(out, open('irelandGeo.json','w'), separators=(',',':'))
print('land rings', len(out['land']), [len(r)//2 for r in out['land']][:5])
print('lakes', [(l['name'], len(l['ring'])//2) for l in out['lakes']])
print('rivers', [len(r['line'])//2 for r in out['rivers']])
import os; print('bytes', os.path.getsize('irelandGeo.json'))
